const express = require('express')
const router = express.Router()
const Controller = require("../controller/controller")

router.get('/', Controller.home)
router.get('/home', Controller.directHome)
router.get('/signup')
router.get('/login')

router.get('/admin/books', Controller.showBook)
router.get('/admin/books/add', Controller.getAddNewBook)
router.post('/admin/books/add', Controller.postAddNewBook)
router.get('/admin/books/edit/:id')
router.post('/admin/books/edit/:id')
router.post('/admin/books/delete/:id')
router.get('/admin/categories')
router.get('/admin/categories/add', Controller.getBookCategories)
router.post('/admin/categories/add', Controller.postBookCategories)
router.get('/admin/categories/edit/:id')
router.post('/admin/categories/edit/:id')
router.post('/admin/categories/delete/:id')

router.get('/user/books', Controller.showBook)
router.get('/user/books/detail')
router.get('/user/buy/:id', Controller.buyBook)
router.get('/user/categories')
module.exports = router;